// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnurvvznrbhqzldxhyzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZudXJ2dnpucmJocXpsZHhoeXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODU2NzAsImV4cCI6MjA2NzQ2MTY3MH0.N-Ieq86TS2ilFtz5MmPZO3KoQMY_MK_P4AL-plgakPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});